baseURL = "/"
title = "XXII Cenáculo NcOrLx"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
googleAnalytics = "G-G847G6KWGL"

[params]
fancyTitle = '<img srcset="/img/logo.png 484w, /img/logo_sm.png 242w" sizes="(max-width: 600px) 242px, 484px"> <br/> XXII Cenáculo NcOrLx'  # title for frontpage, may include image
copyright = "XXII Cenáculo NcOrLx"
source = "https://github.com/CanIBeFii/cenaculo_NcOrLx_site"
# author = "CanIBeFii"
# authorurl = "https://github.com/CanIBeFii"
# description = '1, 2 e 3 de março de 2024. Estás preparado?!' # description below title on frontpage
# startbuttonText = "Inscrições"  # text on the start button
# startbuttonLink = "https://forms.gle/PCM43gawCgQDEYA29"
body_is_markdown = true
# custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Página Inicial"

[[params.menu.main]]
url = 'informacoes-adicionais/local'
title = "Local e Datas"

[[params.menu.main]]
url = 'angariacoes-fundo'
title = "Angariações de Fundo"

[[params.menu.main]]
url = 'informacoes-adicionais/merch'
title = "Merch Cenaculo"

[[params.menu.main]]
url = '/equipa-projeto/'
title = "Equipa Projeto"

[[params.menu.main]]
url = 'informacoes-adicionais/atividades'
title = "Atividades"

[[params.menu.main]]
url = "https://cenaculo.netlify.app/"
title = "Ciclos Passados"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"


[params.one]
enable = true
title = 'Olá Caminheiros!'
href = "/equipa-projeto/"
text = "clica aqui!"
body = '''
Bem-vindo/a ao XXII Ciclo de Cenáculo Oriental! Ao longo deste ciclo é nossa vontade ver-te mais envolvido/a em todo o caminho que a Equipa Projeto percorrerá e a dares voz às tuas vontades e ambições.  
**Envolve-te!**  
O Cenáculo é uma ferramenta pedagógica que te é proporcionada todos os anos para que:

⚜️ Possas conhecer a realidade dos outros Clãs do Núcleo.  
⚜️ Construas verdadeiras pontes nos teus trilhos, quando encontras um escolho intransponível.  
⚜️ Vivas de todos os Caminheiros; Partilhes a tua caminhada e juntos avancem nos Rumos do Homem Novo.

Recorre à Equipa Projeto sempre que precises, pois é de Caminheiros como Tu que ela se compõe. 

A nossa ambição não é que participes, forçosamente, no XXII Ciclo. A nossa ambição é que chegues ao fim do XXII mais desperto, mais concretizado, mais Envolvido!


Canhotas ÉpYcas,  
XXII Ciclo Cenáculo do Núcleo Oriental de Lisboa
'''

special = false


[params.two]
enable = true

[[params.two.section]]
img = "img/angariacoes.jpg"
title = 'ANGARIAÇÕES DE FUNDO'
body = 'Não vão faltar momentos de partilha entre o núcleo!'
button = true

[[params.two.section.link]]
href = "informacoes-adicionais/em-construcao"
text = "JUNTARADA"

[[params.two.section.link]]
href = "informacoes-adicionais/em-construcao"
text = "CINEMA"

[[params.two.section.link]]
href = "informacoes-adicionais/em-construcao"
text = "CAFÉ CONCERTO"

[[params.two.section]]
img = "img/encontro-local.jpg"
title = 'ENCONTRO LOCAL'
body = 'Todos os caminhos vão dar ao Encontro Local :)'
button = true

[[params.two.section.link]]
href = "informacoes-adicionais/em-construcao"
text = "INSCRIÇÃO"

[[params.two.section.link]]
href = "informacoes-adicionais/em-construcao"
text = "INFORMAÇÕES"

[[params.two.section]]
img = "img/equipa-projeto.jpg"
title = 'EQUIPA PROJETO'
body = 'Conhece um pouco sobre cada membro da EP!'
button = true

[[params.two.section.link]]
href = "informacoes-adicionais/em-construcao"
text = "EQUIPA PROJETO"

[[params.two.section]]
img = "img/carta-cenaculo.jpg"
title = 'CARTA DE CENÁCULO'
body = '''Aqui podes aceder à carta de cenáculo.

No reportório podes encontrar diversas atividades para caminheiros, a nível nacional ou regional.'''
button = true

[[params.two.section.link]]
href = "informacoes-adicionais/em-construcao"
text = "CARTA DE CENÁCULO"

[[params.two.section.link]]
href = "informacoes-adicionais/atividades"
text = "REPORTÓRIO DE ATIVIDADES"

[params.contact]
enable = true
title = "Contacta-nos"
body = "Ficaste com alguma dúvida? Envia-nos uma mensagem!"
email = "cenaculo.oriental@escutismo.pt"
subject = "Nova mensagem!"
formspree_form_id = "xqkjlryg"

[params.social]
twitter = ""
facebook = "cenac.ncorlx"
instagram = "cenaculo.ncorlx"
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
